-- Create the produce_lots table
CREATE TABLE
  public.produce_lots (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    origin TEXT NOT NULL,
    "plantingDate" TEXT NOT NULL,
    "harvestDate" TEXT NOT NULL,
    "itemCount" INTEGER NOT NULL,
    farmer JSONB NOT NULL,
    certificates JSONB,
    history JSONB NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
  );

-- Enable Row Level Security (RLS) for the table
ALTER TABLE public.produce_lots ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows public read access to all lots
CREATE POLICY "Allow public read access to all produce lots" ON public.produce_lots FOR
SELECT
  USING (TRUE);

-- Create a policy that allows authenticated users to insert new lots
CREATE POLICY "Allow authenticated users to insert produce lots" ON public.produce_lots FOR INSERT
WITH
  CHECK (auth.role () = 'authenticated');

-- Create a policy that allows authenticated users to update their own lots
CREATE POLICY "Allow authenticated users to update lots" ON public.produce_lots FOR
UPDATE
  USING (auth.role () = 'authenticated')
  WITH
  CHECK (auth.role () = 'authenticated');


-- Create the feedback table
CREATE TABLE public.feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id TEXT NOT NULL,
    feedback_text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Enable RLS for the feedback table
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;

-- Allow anyone to submit feedback
CREATE POLICY "Allow public insert access for feedback"
ON public.feedback
FOR INSERT WITH CHECK (true);

-- Allow anyone to read feedback
CREATE POLICY "Allow public read access for feedback"
ON public.feedback
FOR SELECT USING (true);